name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # expose on localhost
        - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: setup database for tests
      run: ./.ci/setup-test-database.sh
      env:
        PGHOST: 127.0.0.1
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres

    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgres://bot-download-proxy:pass@127.0.0.1:5432/postgres

    - name: Cargo fmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --all-features
